name: Run .NET Tests with Chrome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust to your .NET version if different

      # Step 3: Install Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 4: Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Step 5: Run Tests
      - name: Run Tests
        run: dotnet test --settings chrome.runsettings --logger "trx;LogFileName=test-results.trx"

      # Step 6: Upload Test Results (Optional)
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.trx